---
name: Preflight

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "*"
  

jobs:
  preflight-job:
    name: Preflight Step
    runs-on: ubuntu-latest
    if: >-
      github.ref_name == 'main' 
    steps:
      - run: env
      - run: echo "${{ toJSON(github) }}"
