---
name: Preflight

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "*"
  

jobs:
  preflight-job:
    name: Preflight Step
    runs-on: ubuntu-latest
    if: >-
      (contains(github.event.branches.*.name, 'main')) 
    steps:
      - run: env
